### ISSUE TITLE
Alternative logo proposal

### ISSUE THREAD

**Issue by Carreau** [nteract/logos#2]
SVG: http://carreau.github.io/nteract/

Gif:

![nt](https://cloud.githubusercontent.com/assets/335567/14676868/991ef766-070f-11e6-8c0d-98dcf0ff2e2e.gif)

**Comment by rgbkrk** [comment]
WHOA.

Most excellent 👍

**Comment by rgbkrk** [comment]
Since this predates the work done by @fabric-8, I'll go ahead and close this. Thanks @Carreau!
