### ISSUE TITLE
Create favicon.ico

### ISSUE THREAD

**Issue by rgbkrk** [nteract/logos#6]
We can probably generate it from one of the source or exports of the standalone logo.

/cc @fabric-8, in case there's a tiny version we should use (the App icons?)

**Comment by fabric-8** [comment]
Favicons in all shapes and sizes have just been added https://github.com/nteract/logos/commit/19997367c9b9345a332d99df0b9ab52a8bbdd781

**Comment by rgbkrk** [comment]
Thank you!
